ZOOKEEPER_CLIENT_CONFIG: {}
advanceConfig:
  kafka: {}
  server_properties:
    default.replication.factor: 2
    log.dirs: /data
    log.flush.interval.messages: 10000
    log.flush.interval.ms: 1000
    log.retention.bytes: 1073741824
    log.retention.check.interval.ms: 300000
    log.retention.hours: 6
    message.max.bytes: 100000000
    num.io.threads: 8
    num.network.threads: 3
    num.partitions: 3
    num.recovery.threads.per.data.dir: 1
    replica.fetch.max.bytes: 100000000
    socket.receive.buffer.bytes: 102400
    socket.request.max.bytes: 104857600
    socket.send.buffer.bytes: 102400
    zookeeper.connection.timeout.ms: 6000
appConfig:
  kafka:
    env_list: []
    image: docker.io/corndai1997/kafka:6.0
    priority: 0
    replicas: 3
    resources:
      cpu_limit: 2
      cpu_request: 0.5
      memory_limit: 4Gi
      memory_request: 1Gi
      storage:
        data:
          accessMode: ReadWriteOnce
          limit: {}
          size: 100Gi
          storageClass: silver
        log:
          accessMode: ReadWriteOnce
          limit: {}
          size: 100Gi
          storageClass: silver
    use_host_network: false
transwarpConfig:
  transwarpApplicationPause: false
  transwarpCniNetwork: overlay
  transwarpGlobalIngress:
    httpPort: 80
    httpsPort: 443
  transwarpLicenseAddress: ""
  transwarpMetrics:
    enable: true
