apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": "crd-install"
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: releaseconfigs.apiextensions.transwarp.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apiextensions.transwarp.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1beta1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: releaseconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: releaseconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ReleaseConfig
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - relconf
