apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "walm.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "walm.fullname" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "walm.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      affinity:
      {{- if .Values.affinity }}
      {{- if .Values.affinity.nodeAffinity }}
        nodeAffinity:
{{ toYaml .Values.affinity.nodeAffinity | indent 8 }}      
      {{- end }}
      {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: {{ template "walm.fullname" . }}
                release: {{ .Release.Name }}
            namespaces:
            - {{ .Release.Namespace }}
            {{- if .Values.topologyKey }}
            topologyKey: {{ .Values.topologyKey }}
            {{- end }}
      containers:
      - args:
        - walm
        - serv
        - --config
        - /etc/walm/conf.yaml
        env:
        - name: Pod_Name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: Pod_Namespace
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - mountPath: /etc/walm
          name: walm-conf
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
     {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- else}}
      securityContext: {}
      {{- end }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      {{- if .Values.tolerations }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
     {{- end }}
     {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: conf.yaml
            path: conf.yaml
          name: {{ .Release.Name }}-conf
        name: walm-conf
