
---
# Source: redis/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
    chart: redis-6.1.1
    heritage: Helm
    release: dev-values.yaml
  name: dev-values.yaml-redis
data:
  redis.conf: |-
    # User-supplied configuration:
    # maxmemory-policy volatile-lru
  master.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
  replica.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
---
# Source: redis/templates/health-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
    chart: redis-6.1.1
    heritage: Helm
    release: dev-values.yaml
  name: dev-values.yaml-redis-health
data:
  ping_local.sh: |-
    response=$(
      timeout -s 9 $1 \
      redis-cli \
        -h localhost \
        -p $REDIS_PORT \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
  ping_master.sh: |-
    response=$(
      timeout -s 9 $1 \
      redis-cli \
        -h $REDIS_MASTER_HOST \
        -p $REDIS_MASTER_PORT_NUMBER \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
  ping_local_and_master.sh: |-
    script_dir="$(dirname "$0")"
    exit_status=0
    "$script_dir/ping_local.sh" $1 || exit_status=$?
    "$script_dir/ping_master.sh" $1 || exit_status=$?
    exit $exit_status
---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: dev-values.yaml-redis-master
  labels:
    app: redis
    chart: redis-6.1.1
    release: "dev-values.yaml"
    heritage: "Helm"
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "dev-values.yaml"
    role: master
---
# Source: redis/templates/redis-slave-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: dev-values.yaml-redis-slave
  labels:
    app: redis
    chart: redis-6.1.1
    release: "dev-values.yaml"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "dev-values.yaml"
    role: slave
---
# Source: redis/templates/redis-slave-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-values.yaml-redis-slave
  labels:
    app: redis
    chart: redis-6.1.1
    release: "dev-values.yaml"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
        release: "dev-values.yaml"
        role: slave
        app: redis
  template:
    metadata:
      labels:
        release: "dev-values.yaml"
        chart: redis-6.1.1
        role: slave
        app: redis
      annotations:
        checksum/health: 7b0660b137523bc4d8ed2895fa856193ce8aab94cb5b35d35f4aa5aba6251774
        checksum/configmap: fdd60bda8c6c7aad9a802963c6fba1c7d1f55c5ecc9276de61971c57c4b2aeea
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    spec:
      securityContext:
        fsGroup: 1001
      serviceAccountName: "default"
      containers:
      - name: dev-values.yaml-redis
        image: transwarp/bitnami/redis:4.0.12
        imagePullPolicy: "Always"
        securityContext:
          runAsUser: 1001
        command:
        - /bin/bash
        - -c
        - |
          if [[ -n $REDIS_PASSWORD_FILE ]]; then
            password_aux=`cat ${REDIS_PASSWORD_FILE}`
            export REDIS_PASSWORD=$password_aux
          fi
          if [[ -n $REDIS_MASTER_PASSWORD_FILE ]]; then
            password_aux=`cat ${REDIS_MASTER_PASSWORD_FILE}`
            export REDIS_MASTER_PASSWORD=$password_aux
          fi
          ARGS=("--port" "${REDIS_PORT}")
          ARGS+=("--protected-mode" "no")
          ARGS+=("--include" "/opt/bitnami/redis/etc/redis.conf")
          ARGS+=("--include" "/opt/bitnami/redis/etc/replica.conf")
          /run.sh "${ARGS[@]}"
        env:
        - name: REDIS_REPLICATION_MODE
          value: slave
        - name: REDIS_MASTER_HOST
          value: dev-values.yaml-redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_MASTER_PORT_NUMBER
          value: "6379"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - name: redis
          containerPort: 6379        
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local_and_master.sh 5        
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local_and_master.sh 1
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 0.1
            memory: 256Mi
        volumeMounts:
        - name: health
          mountPath: /health
        - name: redis-data
          mountPath: /data
        - name: config
          mountPath: /opt/bitnami/redis/etc
      volumes:
      - name: health
        configMap:
          name: dev-values.yaml-redis-health
          defaultMode: 0755
      - name: config
        configMap:
          name: dev-values.yaml-redis
      - name: redis-data
        emptyDir: {}
---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: dev-values.yaml-redis-master
  labels:
    app: redis
    chart: redis-6.1.1
    release: "dev-values.yaml"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      release: "dev-values.yaml"
      role: master
      app: redis
  serviceName: dev-values.yaml-redis-master
  template:
    metadata:
      labels:
        release: "dev-values.yaml"
        chart: redis-6.1.1
        role: master
        app: redis
      annotations:
        checksum/health: 7b0660b137523bc4d8ed2895fa856193ce8aab94cb5b35d35f4aa5aba6251774
        checksum/configmap: fdd60bda8c6c7aad9a802963c6fba1c7d1f55c5ecc9276de61971c57c4b2aeea
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    spec:
      securityContext:
        fsGroup: 1001
      hostNetwork: false
      serviceAccountName: "default"
      containers:
      - name: dev-values.yaml-redis
        image: "transwarp/bitnami/redis:4.0.12"
        imagePullPolicy: "Always"
        securityContext:
          runAsUser: 1001
        command:
        - /bin/bash
        - -c
        - |
          if [[ -n $REDIS_PASSWORD_FILE ]]; then
            password_aux=`cat ${REDIS_PASSWORD_FILE}`
            export REDIS_PASSWORD=$password_aux
          fi
          ARGS=("--port" "${REDIS_PORT}")
          ARGS+=("--protected-mode" "no")
          ARGS+=("--include" "/opt/bitnami/redis/etc/redis.conf")
          ARGS+=("--include" "/opt/bitnami/redis/etc/master.conf")
          /run.sh ${ARGS[@]}
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh 5
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh 5
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 0.1
            memory: 256Mi
        volumeMounts:
        - name: health
          mountPath: /health
        - name: redis-data
          mountPath: /data
          subPath: 
        - name: config
          mountPath: /opt/bitnami/redis/etc
      volumes:
      - name: health
        configMap:
          name: dev-values.yaml-redis-health
          defaultMode: 0755
      - name: config
        configMap:
          name: dev-values.yaml-redis
      - name: "redis-data"
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate
---
# Source: redis/autogen-releaseconfig.json.transwarp-jsonnet.yaml
apiVersion: apiextensions.transwarp.io/v1beta1
kind: ReleaseConfig
metadata:
  creationTimestamp: null
  labels:
    auto-gen: "true"
  name: dev-values.yaml
  namespace: ci-test
spec:
  chartAppVersion: 4.0.12
  chartImage: ""
  chartName: redis
  chartVersion: 6.1.1
  configValues:
    cluster:
      enabled: true
      slaveCount: 1
    master:
      persistence:
        enabled: false
    usePassword: false
  dependencies: {}
  dependenciesConfigValues: {}
  outputConfig: {}
  repo: ""
status: {}